### ISSUE TITLE
UnboundLocalError when calling create_database

### ISSUE THREAD

**Issue by radiantone** [mindsdb/mindsdb_python_sdk#60] opened 2023-07-16 11:26 UTC
**Your Environment**

* Python version: 3.10
* Operating system: Pop_OS! 
* Mindsdb Python SDK version: 1.0.4
* Additional info if applicable:
Cannot create database, exception thrown

**Please describe your issue and how we can replicate it**
I attempt to call create_database for my sqllite db, but it fails due to some very poor code in sly (see IDE screenshot)

mdb = server.create_database(
            engine="sqlite",
            name="mydatabase",
            connection_args={
                "db_file": "/root/"+dbname
            }
        )

![image](https://github.com/mindsdb/mindsdb_python_sdk/assets/25509097/2d4894da-14c0-461c-9efa-23f56edde7cb)
![image](https://github.com/mindsdb/mindsdb_python_sdk/assets/25509097/ee91c686-d155-4243-a28f-6330745288d3)

**Comment by radiantone** [comment] 2023-07-17 17:46
sly==0.5

Full trace

`    mdb = server.create_database(
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/mindsdb_sdk/server.py", line 95, in create_database
    self.api.sql_query(ast_query.to_string())
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/mindsdb_sql/parser/ast/base.py", line 34, in to_string
    return self.maybe_add_alias(self.maybe_add_parentheses(self.get_string()), alias=alias)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/mindsdb_sql/parser/dialects/mindsdb/create_database.py", line 46, in get_string
    out_str = f'CREATE{replace_str} DATABASE {self.name.to_string()} WITH ENGINE = {repr(self.engine)}{parameters_str}'
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/mindsdb_sql/parser/ast/base.py", line 34, in to_string
    return self.maybe_add_alias(self.maybe_add_parentheses(self.get_string()), alias=alias)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/mindsdb_sql/parser/ast/select/identifier.py", line 77, in get_string
    return self.parts_to_str()
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/mindsdb_sql/parser/ast/select/identifier.py", line 57, in parts_to_str
    reserved_words = get_reserved_words()
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/mindsdb_sql/parser/ast/select/identifier.py", line 26, in get_reserved_words
    from mindsdb_sql.parser.lexer import SQLLexer
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/mindsdb_sql/parser/lexer.py", line 2, in <module>
    from sly import Lexer
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/sly/__init__.py", line 2, in <module>
    from .lex import *
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/sly/lex.py", line 183, in <module>
    class Lexer(metaclass=LexerMeta):
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/sly/lex.py", line 180, in __new__
    cls._build()
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/sly/lex.py", line 307, in _build
    part = f'(?P<{tokname}>{pattern})'
UnboundLocalError: local variable 'pattern' referenced before assignment
`

**Comment by ea-rus** [comment] 2023-07-18 13:59
This error appears only in debugger, right? I think I also encountered with it

**Comment by radiantone** [comment] 2023-07-24 07:30
It appears without debugger too.

**Comment by ea-rus** [comment] 2023-07-24 09:23
will be fixed in next release of mindsdb_sql

**Comment by radiantone** [comment] 2023-07-24 23:50
Thank you!! Would you happen to know when that will be released?

**Comment by ea-rus** [comment] 2023-07-27 14:16
mindsdb_sql was released

**Closed** 2023-07-27 14:16 UTC

**Comment by darrenenq** [comment] 2023-08-09 12:05
Thank you so much for this! :)

**Comment by darrenenq** [comment] 2023-08-09 12:34
#0 33.09 The conflict is caused by:
#0 33.09     The user requested mindsdb-sql==0.7.0
#0 33.09     mindsdb-sdk 1.0.4 depends on mindsdb-sql<0.7.0 and >=0.6.1
