### ISSUE TITLE
Cannot create model

### ISSUE THREAD

**Issue by radiantone** [mindsdb/mindsdb_python_sdk#77] opened 2023-10-07 10:24 UTC
Does this SDK work at all? Seems like its broken

Tried to create a model using a simple SQL query "select * from prices" and looks like its introducing parens or something.

* Python version: 3.10.12
* Operating system: Pop!_OS(Ubuntu) 22.04
* Mindsdb Python SDK version: 
mindsdb-sdk==1.0.4
mindsdb-sql==0.6.7

* Additional info if applicable:

**Please describe your issue and how we can replicate it**

  File "/home/darren/PycharmProjects/pyfi/pyfi/server/api.py", line 1747, in create_model
    project.create_model(name=model, predict=data["column"], query=data['query'])
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/mindsdb_sdk/project.py", line 410, in create_model
    df = self.query(ast_query.to_string()).fetch()
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/mindsdb_sdk/query.py", line 29, in fetch
    return self.api.sql_query(self.sql, self.database)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/mindsdb_sdk/connectors/rest_api.py", line 11, in wrapper
    return fnc(self, *args, **kwargs)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.10/site-packages/mindsdb_sdk/connectors/rest_api.py", line 82, in sql_query
    raise RuntimeError(data['error_message'])
RuntimeError: SQL statement cannot be parsed by mindsdb_sql - CREATE PREDICTOR modeltest (select * from prices) PREDICT prices: Syntax error at token LPAREN: "("

**Comment by ZoranPandovski** [comment] 2023-10-08 14:48
Can you share the code example please?

**Comment by ea-rus** [comment] 2024-02-05 08:04
Let's close it and open again when we have more information

**Closed by ea-rus** 2024-02-05 08:04 UTC
Labels: bug, question

**Comment by kiuyaku** [comment] 2024-07-10 05:52
> Let's close it and open again when we have more information
@ea-rus 

Hi sir, I can't create a model either, I get an error after using models.create.

`>CREATE PREDICTOR my_project.my_model (SELECT * FROM my_db.my_article) PREDICT `id`
----------------------------------------^
Expected symbol: "PREDICT"
`

I've looked for a lot of examples and issues that can't solve my problem.

Here's my code:
I want to use the default engine and insert my data to create a model.
Is the following usage correct? Or are there other steps?
Can you please help me see where the error is? Thank you sosososososososo much.
`
project = server.get_project('my_project')
table = mysql_db.tables.get('my_article')
model = project.models.create(
            'my_model',
            predict='id',
            query=table,
        )
`

**Comment by ea-rus** [comment] 2024-07-10 10:08
@kiuyaku, please try to update mindsdb_sql to the latest version

**Comment by ea-rus** [comment] 2024-07-10 10:10
This could be the cause: https://github.com/mindsdb/mindsdb_python_sdk/pull/129

**Comment by kiuyaku** [comment] 2024-07-11 02:25
> @kiuyaku, please try to update mindsdb_sql to the latest version

OK! I'm just going to give it a try! thank you very much!
